ARCH_STM32 = 1
PROC_STM32F4 = 1

# just to let eclipse get the picture
STM32F4XX = 1
USE_STDPERIPH_DRIVER = 1

CONFIG_MEMOPS = 1
CONFIG_VARCALL = 1
CONFIG_MATH = 1
CONFIG_MINIUTILS = 1
CONFIG_SHARED_MEM = 1

CONFIG_TASK_QUEUE = 1
CONFIG_RINGBUFFER = 1

CONFIG_GPIO = 1
CONFIG_USB_VCD = 1
CONFIG_UART = 1
CONFIG_I2C = 1
CONFIG_I2C_DEVICE = 1
CONFIG_LSM303 = 1
CONFIG_WIFI232 = 1

CONFIG_SPI = 1
CONFIG_SPI_DEVICE = 1

CONFIG_BOOTLOADER = 1

CONFIG_OS = 1

CONFIG_HEAP = 1

include ../generic/system/include.mk