// Auto generated file, do not tamper
#ifdef INCLUDE_CONFIG_HEADER
#ifndef _CONFIG_HEADER_H
#define _CONFIG_HEADER_H
#define ARCH_STM32
#define PROC_STM32F4
#define STM32F4XX
#define USE_STDPERIPH_DRIVER
#define CONFIG_MEMOPS
#define CONFIG_VARCALL
#define CONFIG_MATH
#define CONFIG_MINIUTILS
#define CONFIG_SHARED_MEM
#define CONFIG_TASK_QUEUE
#define CONFIG_RINGBUFFER
#define CONFIG_USB_VCD
#define CONFIG_UART
#define CONFIG_I2C
#define CONFIG_I2C_DEVICE
#define CONFIG_LSM303
#define CONFIG_WIFI232
#define CONFIG_SPI
#define CONFIG_SPI_DEVICE
#define CONFIG_BOOTLOADER
#define CONFIG_OS
#define CONFIG_HEAP
#endif
#endif
